# Generated by Django 5.1.3 on 2024-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressdetector', '0003_alter_user_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
