# Generated by Django 5.1.3 on 2024-11-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressdetector', '0004_alter_user_cpassword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='stressdetector_user',
        ),
    ]
