# Generated by Django 5.1.3 on 2024-11-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressdetector', '0006_remove_user_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
