# Generated by Django 5.1.3 on 2024-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressdetector', '0008_stressresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoring_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('limb_movement', models.FloatField()),
                ('blood_oxygen', models.FloatField()),
                ('eye_movements', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('heart_rate', models.FloatField()),
            ],
        ),
    ]
